package FileSystemApp;


/**
* FileSystemApp/ClientToServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sunday, December 6, 2020 10:50:01 PM EST
*/

public abstract class ClientToServerPOA extends org.omg.PortableServer.Servant
 implements FileSystemApp.ClientToServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("readLocalFile", new java.lang.Integer (0));
    _methods.put ("writeLocalFile", new java.lang.Integer (1));
    _methods.put ("shutdown", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FileSystemApp/ClientToServer/readLocalFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.readLocalFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FileSystemApp/ClientToServer/writeLocalFile
       {
         String fileName = in.read_string ();
         String message = in.read_string ();
         boolean $result = false;
         $result = this.writeLocalFile (fileName, message);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // FileSystemApp/ClientToServer/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FileSystemApp/ClientToServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientToServer _this() 
  {
    return ClientToServerHelper.narrow(
    super._this_object());
  }

  public ClientToServer _this(org.omg.CORBA.ORB orb) 
  {
    return ClientToServerHelper.narrow(
    super._this_object(orb));
  }


} // class ClientToServerPOA
