package FileSystemApp;


/**
* FileSystemApp/ClientToServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sunday, December 6, 2020 10:50:01 PM EST
*/

public interface ClientToServerOperations 
{
  String readLocalFile (String fileName);
  boolean writeLocalFile (String fileName, String message);
  void shutdown ();
} // interface ClientToServerOperations
