package FileSystemApp;

/**
* FileSystemApp/ClientToServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sunday, December 6, 2020 10:50:01 PM EST
*/

public final class ClientToServerHolder implements org.omg.CORBA.portable.Streamable
{
  public FileSystemApp.ClientToServer value = null;

  public ClientToServerHolder ()
  {
  }

  public ClientToServerHolder (FileSystemApp.ClientToServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSystemApp.ClientToServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSystemApp.ClientToServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSystemApp.ClientToServerHelper.type ();
  }

}
