package FileSystemApp;


/**
* FileSystemApp/ServerToServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sunday, December 6, 2020 10:50:01 PM EST
*/

abstract public class ServerToServerHelper
{
  private static String  _id = "IDL:FileSystemApp/ServerToServer:1.0";

  public static void insert (org.omg.CORBA.Any a, FileSystemApp.ServerToServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FileSystemApp.ServerToServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FileSystemApp.ServerToServerHelper.id (), "ServerToServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FileSystemApp.ServerToServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerToServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FileSystemApp.ServerToServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FileSystemApp.ServerToServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileSystemApp.ServerToServer)
      return (FileSystemApp.ServerToServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FileSystemApp._ServerToServerStub stub = new FileSystemApp._ServerToServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FileSystemApp.ServerToServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileSystemApp.ServerToServer)
      return (FileSystemApp.ServerToServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FileSystemApp._ServerToServerStub stub = new FileSystemApp._ServerToServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
