package FileSystemApp;

/**
* FileSystemApp/ServerToServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sunday, December 6, 2020 10:50:01 PM EST
*/

public final class ServerToServerHolder implements org.omg.CORBA.portable.Streamable
{
  public FileSystemApp.ServerToServer value = null;

  public ServerToServerHolder ()
  {
  }

  public ServerToServerHolder (FileSystemApp.ServerToServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSystemApp.ServerToServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSystemApp.ServerToServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSystemApp.ServerToServerHelper.type ();
  }

}
