package FileSystemApp;


/**
* FileSystemApp/ServerToServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sunday, December 6, 2020 10:50:01 PM EST
*/

public abstract class ServerToServerPOA extends org.omg.PortableServer.Servant
 implements FileSystemApp.ServerToServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("fetchRemoteFile", new java.lang.Integer (0));
    _methods.put ("readRemoteFile", new java.lang.Integer (1));
    _methods.put ("lockAndWrite", new java.lang.Integer (2));
    _methods.put ("fileExists", new java.lang.Integer (3));
    _methods.put ("checkLock", new java.lang.Integer (4));
    _methods.put ("sayOnline", new java.lang.Integer (5));
    _methods.put ("pingServers", new java.lang.Integer (6));
    _methods.put ("killAllORB", new java.lang.Integer (7));
    _methods.put ("shutdown", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FileSystemApp/ServerToServer/fetchRemoteFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.fetchRemoteFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FileSystemApp/ServerToServer/readRemoteFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.readRemoteFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // FileSystemApp/ServerToServer/lockAndWrite
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.lockAndWrite (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // FileSystemApp/ServerToServer/fileExists
       {
         String title = in.read_string ();
         boolean $result = false;
         $result = this.fileExists (title);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // FileSystemApp/ServerToServer/checkLock
       {
         String fileName = in.read_string ();
         boolean $result = false;
         $result = this.checkLock (fileName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // FileSystemApp/ServerToServer/sayOnline
       {
         String $result = null;
         $result = this.sayOnline ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // FileSystemApp/ServerToServer/pingServers
       {
         this.pingServers ();
         out = $rh.createReply();
         break;
       }

       case 7:  // FileSystemApp/ServerToServer/killAllORB
       {
         this.killAllORB ();
         out = $rh.createReply();
         break;
       }

       case 8:  // FileSystemApp/ServerToServer/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FileSystemApp/ServerToServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerToServer _this() 
  {
    return ServerToServerHelper.narrow(
    super._this_object());
  }

  public ServerToServer _this(org.omg.CORBA.ORB orb) 
  {
    return ServerToServerHelper.narrow(
    super._this_object(orb));
  }


} // class ServerToServerPOA
