package FileSystemApp;


/**
* FileSystemApp/ServerToServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sunday, December 6, 2020 10:50:01 PM EST
*/

public interface ServerToServerOperations 
{
  String fetchRemoteFile (String fileName);
  String readRemoteFile (String fileName);
  String lockAndWrite (String fileName);
  boolean fileExists (String title);
  boolean checkLock (String fileName);
  String sayOnline ();
  void pingServers ();
  void killAllORB ();
  void shutdown ();
} // interface ServerToServerOperations
