package DFSApp;


/**
* DFSApp/_ServerToServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DFS.idl
* Thursday, November 29, 2018 11:00:20 AM EST
*/

public class _ServerToServerStub extends org.omg.CORBA.portable.ObjectImpl implements DFSApp.ServerToServer
{

  public String readFile (String fileTitle) throws DFSApp.ServerToServerPackage.FileNotFoundFailure, DFSApp.ServerToServerPackage.FileLockedForWriteFailure
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("readFile", true);
                $out.write_string (fileTitle);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:DFSApp/ServerToServer/FileNotFoundFailure:1.0"))
                    throw DFSApp.ServerToServerPackage.FileNotFoundFailureHelper.read ($in);
                else if (_id.equals ("IDL:DFSApp/ServerToServer/FileLockedForWriteFailure:1.0"))
                    throw DFSApp.ServerToServerPackage.FileLockedForWriteFailureHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return readFile (fileTitle        );
            } finally {
                _releaseReply ($in);
            }
  } // readFile

  public String readFileAndLockForWrite (String fileTitle) throws DFSApp.ServerToServerPackage.FileNotFoundFailure, DFSApp.ServerToServerPackage.FileLockedForWriteFailure
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("readFileAndLockForWrite", true);
                $out.write_string (fileTitle);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:DFSApp/ServerToServer/FileNotFoundFailure:1.0"))
                    throw DFSApp.ServerToServerPackage.FileNotFoundFailureHelper.read ($in);
                else if (_id.equals ("IDL:DFSApp/ServerToServer/FileLockedForWriteFailure:1.0"))
                    throw DFSApp.ServerToServerPackage.FileLockedForWriteFailureHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return readFileAndLockForWrite (fileTitle        );
            } finally {
                _releaseReply ($in);
            }
  } // readFileAndLockForWrite

  public void lockFileForWrite (String fileTitle)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("lockFileForWrite", false);
                $out.write_string (fileTitle);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                lockFileForWrite (fileTitle        );
            } finally {
                _releaseReply ($in);
            }
  } // lockFileForWrite

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DFSApp/ServerToServer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServerToServerStub
