package DFSApp;


/**
* DFSApp/ClientToServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DFS.idl
* Thursday, November 29, 2018 11:00:20 AM EST
*/

public interface ClientToServerOperations 
{
  String sayHello ();
  int openFileForRead (String fileTitle) throws DFSApp.ClientToServerPackage.FileNotFoundFailure;
  String readFromFile (int fileID, int location, int length);
  void closeFile (int fileID);
  void shutdown ();
} // interface ClientToServerOperations
