package DFSApp;

/**
* DFSApp/ClientToServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DFS.idl
* Thursday, November 29, 2018 11:00:20 AM EST
*/

public final class ClientToServerHolder implements org.omg.CORBA.portable.Streamable
{
  public DFSApp.ClientToServer value = null;

  public ClientToServerHolder ()
  {
  }

  public ClientToServerHolder (DFSApp.ClientToServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DFSApp.ClientToServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DFSApp.ClientToServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DFSApp.ClientToServerHelper.type ();
  }

}
