package DFSApp;


/**
* DFSApp/ClientToServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DFS.idl
* Thursday, November 29, 2018 11:00:20 AM EST
*/

public abstract class ClientToServerPOA extends org.omg.PortableServer.Servant
 implements DFSApp.ClientToServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("openFileForRead", new java.lang.Integer (1));
    _methods.put ("readFromFile", new java.lang.Integer (2));
    _methods.put ("closeFile", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DFSApp/ClientToServer/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DFSApp/ClientToServer/openFileForRead
       {
         try {
           String fileTitle = in.read_string ();
           int $result = (int)0;
           $result = this.openFileForRead (fileTitle);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (DFSApp.ClientToServerPackage.FileNotFoundFailure $ex) {
           out = $rh.createExceptionReply ();
           DFSApp.ClientToServerPackage.FileNotFoundFailureHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // DFSApp/ClientToServer/readFromFile
       {
         int fileID = in.read_long ();
         int location = in.read_long ();
         int length = in.read_long ();
         String $result = null;
         $result = this.readFromFile (fileID, location, length);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DFSApp/ClientToServer/closeFile
       {
         int fileID = in.read_long ();
         this.closeFile (fileID);
         out = $rh.createReply();
         break;
       }

       case 4:  // DFSApp/ClientToServer/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DFSApp/ClientToServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientToServer _this() 
  {
    return ClientToServerHelper.narrow(
    super._this_object());
  }

  public ClientToServer _this(org.omg.CORBA.ORB orb) 
  {
    return ClientToServerHelper.narrow(
    super._this_object(orb));
  }


} // class ClientToServerPOA
