package DFSApp;


/**
* DFSApp/ServerToServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DFS.idl
* Thursday, November 29, 2018 11:00:20 AM EST
*/

public interface ServerToServerOperations 
{
  String readFile (String fileTitle) throws DFSApp.ServerToServerPackage.FileNotFoundFailure, DFSApp.ServerToServerPackage.FileLockedForWriteFailure;
  String readFileAndLockForWrite (String fileTitle) throws DFSApp.ServerToServerPackage.FileNotFoundFailure, DFSApp.ServerToServerPackage.FileLockedForWriteFailure;
  void lockFileForWrite (String fileTitle);
  void shutdown ();
} // interface ServerToServerOperations
