package DFSApp;

/**
* DFSApp/ServerToServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DFS.idl
* Thursday, November 29, 2018 11:00:20 AM EST
*/

public final class ServerToServerHolder implements org.omg.CORBA.portable.Streamable
{
  public DFSApp.ServerToServer value = null;

  public ServerToServerHolder ()
  {
  }

  public ServerToServerHolder (DFSApp.ServerToServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DFSApp.ServerToServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DFSApp.ServerToServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DFSApp.ServerToServerHelper.type ();
  }

}
