all: part1 part2 part3

list:
		gcc -g list.c -o list	

test-l:
		./list a -a b -b c -c d -d e -e f -f

part1:
		gcc -g part1.c -o part1

test-1:
		./part1 a -a b -b c -c d -d e -e f -f		

part2:
		gcc -g part2.c -o part2

test-2:
		./part2 a -a b -b c -c d -d e -e f -f

part3:
		gcc -g part3.c -o part3

test-3:
		./part3

clean:
		rm -f part1 part2 part3 list