/*
 Programmer: Andrew Januszko                   Date Completed: February 1, 2019
 Instructor: Chen Huo                          Class: ENGR 120-03

 A program to calulate  power (in megawatts) generated by a hydroelectric dam.
*/
#include <stdio.h> /* printf, scanf definitions. */
#define GRAVITY 9.80 /* holds the value of gravity. */
#define DAM_EFFICIENCY 0.90 /* holds the constant of efficiency for the dam. */
#define WATT_TO_MEGAWATT (1.0/1000.0) /* defines the relation of watts to megawatts. */

int main(void){

  double height, /* holds the height of the dam. */
         flowRate, /* holds the flow rate of the dam. */
         power, /* holds the power of the dam. */
         megaWatts; /* holds the power, in megawatts, of the dam. */

  /* Ask the user for the height of the dam. */
  printf("Enter height of dam: ");
  scanf("%lf", &height); /* Scan for user input, store it into height (double). */

  /* Ask the user for the flow rate of the dam. */
  printf("Enter rate (m^3/s): ");
  scanf("%lf", &flowRate); /* Scan for user input, store it into flowRate (double). */

  power = height * flowRate * GRAVITY * DAM_EFFICIENCY; /* Calculate power in watts (w). */
  megaWatts = power * WATT_TO_MEGAWATT; /* Convert from watts (w) to megawatts (Mw). */

  /* Return the total work value for the dam (in megawatts). */
  printf("Total work: %.2f MW\n", megaWatts);

  /* Return 0. */
  return(0);
}
