// Mocks generated by Mockito 5.3.2 from annotations
// in game_manager/test/pages/questions/questions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dio/dio.dart' as _i2;
import 'package:game_manager/repository/questions/question.dart';
import 'package:game_manager/repository/questions/get_all_questions_request.dart'
    as _i13;
import 'package:game_manager/repository/questions/get_all_questions_response.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

import 'questions_test.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAllQuestionsResponse_4 extends _i1.SmartFake
    implements _i6.GetAllQuestionsResponse {
  _FakeGetAllQuestionsResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuestionsRepositoryTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestionsRepositoryTest extends _i1.Mock
    implements _i7.QuestionsRepositoryTest {
  MockQuestionsRepositoryTest() {
    _i1.throwOnMissingStub(this);
  }

  _i8.Future<_i6.GetAllQuestionsResponse> getAllQuestions(
          _i13.GetAllQuestionsRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllQuestions,
          [request],
        ),
        returnValue: _i8.Future<_i6.GetAllQuestionsResponse>.value(
            _FakeGetAllQuestionsResponse_4(
          this,
          Invocation.method(
            #getAllQuestions,
            [request],
          ),
        )),
      ) as _i8.Future<_i6.GetAllQuestionsResponse>);
}
